14.3 Testing Exceptional Exceptions
 Is the exception thrown?
 - Now, normally we write tests for return values. But you can also write tests to verify that the correct exception is thrown. So let's do that in GithubServiceTest. Hmm... This first test has a lot of the logic we'll need. Copy that and paste it at the bottom. Change the name to testExceptionThrownWithUnknownLabel and remove the arguments. Inside, take out the assertion leaving just the call to $service->getHealthReport(). And instead of $dinoName, pass in Maverick. For $mockResponse, remove Daisy from willReturn() and change Mavericks label from Healthy to Drowsy
 Alrighty, lets give this a shot:

  ./vendor/bin/phpunit
 And... Ouch! GithubServiceTest failed because of a:

  RuntimeException: Drowsy is an unknown status label!

 This is actually good news. It means GithubService is doing exactly what we want it to do